### ISSUE TITLE
Building nodejs-slim takes a long time in MacOS

### ISSUE THREAD

**Issue by xixiaofinland** [rfaulhaber/sfdx-nix#8]
Hi Ryan,

When I update sfdx-nix version in MacOS, the building `nodejs-slim` step takes long (up to 1 hour) in my MacOS. I use nix-darwin as in the screenshot.

<img width="722" alt="Screenshot 2024-09-02 at 10 20 17" src="https://github.com/user-attachments/assets/a777a832-11d6-43e6-b159-c6147a0287c8">

However, this slowness doesn't happen in my NixOS where I also use sfdx-nix and almost the same dotfiles configration. Not sure if you have insights? 

Br,
Xi

**Comment by xixiaofinland** [comment]
I start to use cachix for these big binaries, let's see if this is a good solution.

**Comment by rfaulhaber** [comment]
Hmm I'll take a look into this, I haven't built it on macOS recently, but cachix certainly might help in this case.

**Comment by rfaulhaber** [comment]
Are you still experiencing this issue? I can't reproduce it on my MacBook and I'm wondering if you caught Hydra at the wrong time (sometimes Nix will build things from source if the latest version of a package hasn't been built in Hydra yet)

**Comment by xixiaofinland** [comment]
It's resolved by introducing caching. I put the post on reddit there: https://www.reddit.com/r/Nix/comments/1f8u3tz/  

It's an exciting problem, unfortunately i didnt' have time to dig into this. I don't think this issue is participarly caused by sfdx-nix.

I'm closing it now, thanks for your help :)!

**Comment by rfaulhaber** [comment]
Haha yes it looks like an exciting problem! I skimmed the discussion and the thing about caching makes sense. I can't say I've ever run into that issue but I am vaguely aware of it. Well anyway, relieved to hear it's definitely not the flake's fault!
